server:
    #项目启动端口
    port: 8090
    tomcat: 
      # tomcat的URI编码
      uri-encoding: utf-8
      # tomcat最大线程数，默认为200
      max-threads: 1000
      
spring: 
    datasource:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://119.23.247.225:3306/blogforum_user?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
        
        
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: 
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 5000
        #开启监控因为使用加密所以需要加config stat为sql监控 
        filters: config,stat,wall,log4j
    #redis
    redis: 
      # Redis服务器地址
      hostName: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码
      password: 123456
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        maxActive: 8
        # 连接池中的最大空闲连接
        minIdle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWait: -1
        # 连接池中的最小空闲连接
        maxIdle: 8
      # 连接超时时间（毫秒）
      timeout: 20000
      
    #邮件发送配置
    mail:
      host: smtp.126.com
      username: blogwangwendi@126.com
      password: qaz123456
      default-encoding: UTF-8
      #设置通信端口为465加密端口
      port: 465
      properties:
      #使用ssl加密设置
        mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        
mybatis:
    type-aliases-package: com.blogforum.sso.pojo.entity
    mapper-locations: classpath:mapper/*.xml
    
    
#sso服务器地址
myValue: 
  ssoServiceUrl: http://119.23.247.225:8011
  #session过期时间
  session_time: 1800
  #注册时保存到redis的值
  REGISTER_KEY: register_key






